global:
  scrape_interval: 15s # 15초마다 긁어감

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/api/actuator/prometheus' # 스프링 부트가 데이터 주는 주소
    static_configs:
      # 여기에 백엔드 서버(EB 인스턴스)의 "프라이빗 IP"와 "포트"를 적음
      # 예: targets: ['10.0.1.154:5000', '10.0.2.93:5000']
#      - targets: ['localhost:5000']

      # - 도커가 내 PC(Host)를 찾음 (성공)
      - targets: [ 'host.docker.internal:5000' ]