global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      # [핵심] 리스트 형태로 여러 대 등록
      # 예: 서버 A(10.0.1.10), 서버 B(10.0.1.11)
      # EC2 ip 변경 되면 수정 필요
      - targets: ['10.0.0.5:5000', '10.0.0.12:5000']