apiVersion: 1

datasources:
  # 1. 프로메테우스 (기존 설정 유지)
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  # [추가] 2. Loki 설정
  - name: Loki
    type: loki
    access: proxy
    # Docker Compose 내부 서비스명(loki)과 포트(3100) 사용
    url: http://loki:3100
    jsonData:
      maxLines: 1000